In [1]:
import os
HOME = os.getcwd()
print(HOME)

/kaggle/working


In [2]:
!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.196 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5771.7/8062.4 GB disk)


In [3]:
from ultralytics import YOLO

from IPython.display import display, Image

In [4]:
%cd {HOME}
!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source='https://media.roboflow.com/notebooks/examples/dog.jpeg' save=True

/kaggle/working
100%|██████████████████████████████████████| 6.23M/6.23M [00:00<00:00, 93.9MB/s]
Ultralytics YOLOv8.0.196 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

100%|████████████████████████████████████████| 104k/104k [00:00<00:00, 60.2MB/s]
image 1/1 /kaggle/working/dog.jpeg: 640x384 1 person, 1 car, 1 dog, 104.2ms
Speed: 11.6ms preprocess, 104.2ms inference, 223.8ms postprocess per image at shape (1, 3, 640, 384)
Results saved to runs/detect/predict
💡 Learn more at https://docs.ultralytics.com/modes/predict


In [5]:
model = YOLO(f'{ HOME }/yolov8n.pt')
results = model.predict(source='https://media.roboflow.com/notebooks/examples/dog.jpeg', conf=0.25)


Found https://media.roboflow.com/notebooks/examples/dog.jpeg locally at dog.jpeg
image 1/1 /kaggle/working/dog.jpeg: 640x384 1 person, 1 car, 1 dog, 79.2ms
Speed: 5.2ms preprocess, 79.2ms inference, 165.2ms postprocess per image at shape (1, 3, 640, 384)


In [6]:
results[0].boxes.xyxy

tensor([[   0.0000,  314.4716,  625.0755, 1278.1947],
        [  55.1730,  250.0220,  648.1080, 1266.2720],
        [ 633.2291,  719.5391,  701.0538,  786.0336]], device='cuda:0')

In [7]:
results[0].boxes.conf

tensor([0.7271, 0.2907, 0.2846], device='cuda:0')

In [8]:
results[0].boxes.cls

tensor([ 0., 16.,  2.], device='cuda:0')

In [9]:
!mkdir {HOME}/datasets
%cd {HOME}/datasets

# !pip install roboflow --quiet

# from roboflow import Roboflow
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="SxBvSKF9INyOitx38JNa")
project = rf.workspace("njit-6mjxn").project("drone-detection-fmgs5")
version = project.version(1)
dataset = version.download("yolov5")

/kaggle/working/datasets
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 4.3 MB/s eta 0:00:00
  Attempting uninstall: idna
    Found existing installation: idna 3.6
    Uninstalling idna-3.6:
      Successfully uninstalled idna-3.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-decision-forests 1.8.1 requires wurlitzer, which is not installed.
jupyterlab 4.2.3 requires jupyter-lsp>=2.0.0, but you have jupyter-lsp 1.5.1 which is incompatible.
jupyterlab-lsp 5.1.0 requires jupyter-lsp>=2.0.0, but you have jupyter-lsp 1.5.1 which is incompatible.
tensorflow 2.15.0 requires keras<2.16,>=2.15.0, but you have keras 3.4.1 which is incompatible.
ydata-profiling 4.6.4 requires numpy<1.26,>=1.16


Extracting Dataset Version Zip to Drone-Detection-1 in yolov5pytorch:: 100%|██████████| 34998/34998 [00:04<00:00, 7112.69it/s]


In [10]:
!cat /kaggle/working/datasets/Drone-Detection-1/data.yaml

names:
- drone
nc: 1
roboflow:
  license: CC BY 4.0
  project: drone-detection-fmgs5
  url: https://universe.roboflow.com/njit-6mjxn/drone-detection-fmgs5/dataset/1
  version: 1
  workspace: njit-6mjxn
test: ../test/images
train: Drone-Detection-1/train/images
val: Drone-Detection-1/valid/images


In [11]:
from pathlib import Path
yaml_content = f'''
names:
- drone
nc: 1
roboflow:
  license: CC BY 4.0
  project: drone-detection-fmgs5
  url: https://universe.roboflow.com/njit-6mjxn/drone-detection-fmgs5/dataset/1
  version: 1
  workspace: njit-6mjxn
test: /kaggle/working/datasets/Drone-Detection-1/test/images
train: /kaggle/working/datasets/Drone-Detection-1/train/images
val: /kaggle/working/datasets/Drone-Detection-1/valid/images
    '''

with Path('/kaggle/working/datasets/Drone-Detection-1/data.yaml').open('w') as f:
    f.write(yaml_content)

In [12]:
!cat /kaggle/working/datasets/Drone-Detection-1/data.yaml


names:
- drone
nc: 1
roboflow:
  license: CC BY 4.0
  project: drone-detection-fmgs5
  url: https://universe.roboflow.com/njit-6mjxn/drone-detection-fmgs5/dataset/1
  version: 1
  workspace: njit-6mjxn
test: /kaggle/working/datasets/Drone-Detection-1/test/images
train: /kaggle/working/datasets/Drone-Detection-1/train/images
val: /kaggle/working/datasets/Drone-Detection-1/valid/images
    

In [15]:
%cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=25 imgsz=800 plots=True

/kaggle/working
New https://pypi.org/project/ultralytics/8.2.66 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.196 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: task=detect, mode=train, model=yolov8s.pt, data=/kaggle/working/datasets/Drone-Detection-1/data.yaml, epochs=25, patience=50, batch=16, imgsz=800, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line

In [14]:
# from IPython.display import FileLink
# FileLink(r'/kaggle/working/runs/detect/train2/weights/best.pt')
